"""
Agent E: Cypher Generation Validator

Tests the actual Cypher queries being generated by the multi-agent system.

Process ID: f96d6d53-8257-4d3c-86b1-279f0e3ad069

This script:
1. Directly calls run_fewshot_cypher_generation() from multiagent_cypher_service.py
2. Captures the generated Cypher queries
3. Validates them against Neo4j syntax
4. Checks if generated Cyphers are using correct node types (Cell vs Line)
5. Verifies the structural probe is working correctly
6. Tests if hard constraints are being enforced

Created: 2026-02-20
"""

import os
import sys
import json
import re
import logging
from typing import Dict, List, Any, Tuple
from datetime import datetime
from neo4j import GraphDatabase

# Add backend to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from services.multiagent_cypher_service import (
    run_fewshot_cypher_generation,
    Neo4jTools,
    WeaviateTools,
    extract_hard_constraints,
    verify_topology,
    NEO4J_URI,
    NEO4J_USERNAME,
    NEO4J_PASSWORD
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# =============================================================================
# CONFIGURATION
# =============================================================================

PROCESS_ID = "f96d6d53-8257-4d3c-86b1-279f0e3ad069"

# Test queries with expected node type usage
TEST_QUERIES = [
    {
        "query": "Get Ges.-Mittel. row values",
        "expected_node": "Cell",
        "description": "Row extraction - should use Cell nodes from tables",
        "validation_notes": "Ges.-Mittel. is a row label typically found in tables"
    },
    {
        "query": "What is the Batch Name?",
        "expected_node": "Cell|Line",  # Could be either
        "description": "Simple lookup - could be Line or Cell depending on document structure",
        "validation_notes": "Batch Name might appear in paragraph text (Line) or table (Cell)"
    },
    {
        "query": "Show all table headers",
        "expected_node": "Cell",
        "description": "Header extraction - should use Cell with row_index=0 or 1",
        "validation_notes": "Headers are in Cell nodes with row_index IN [0, 1]"
    },
    {
        "query": "Get data from the first table on page 2",
        "expected_node": "Cell",
        "description": "Table + page filter - should use Table + Cell with page constraint",
        "validation_notes": "Requires Document->Page->Table->Cell path with page_num filter"
    }
]


# =============================================================================
# CYPHER SYNTAX VALIDATOR
# =============================================================================

class CypherSyntaxValidator:
    """Validates Cypher query syntax without executing."""

    # Valid node types in the schema
    VALID_NODE_TYPES = ['Document', 'Page', 'Table', 'Cell', 'MergedCell', 'Line', 'Section', 'Word', 'KV']

    # Valid relationships
    VALID_RELATIONSHIPS = [
        'HAS_PAGE', 'CONTAINS_TABLE', 'HAS_CELL', 'CONTAINS_LINE',
        'CONTAINS_SECTION', 'SAME_ROW', 'SAME_COL', 'HAS_WORD', 'HAS_KV'
    ]

    # Common Cypher syntax errors
    SYNTAX_ERROR_PATTERNS = [
        (r'MATCH\s+\(\s*\)', "Empty MATCH pattern"),
        (r'WHERE\s+AND', "WHERE followed by AND without condition"),
        (r'\)\s*-\s*\[\s*:\s*\]', "Empty relationship type"),
        (r'RETURN\s*$', "RETURN with no columns"),
        (r'ORDER BY\s*$', "ORDER BY with no columns"),
        (r'\s+AS\s*$', "AS with no alias"),
        (r'collect\(\s*\)', "Empty collect()"),
        (r'\$\s*\)', "Unterminated parameter"),
    ]

    def __init__(self):
        self.errors = []
        self.warnings = []

    def validate(self, cypher: str) -> Tuple[bool, List[str], List[str]]:
        """
        Validate Cypher syntax.

        Returns:
            Tuple of (is_valid, errors, warnings)
        """
        self.errors = []
        self.warnings = []

        if not cypher or not cypher.strip():
            self.errors.append("Empty Cypher query")
            return False, self.errors, self.warnings

        # Check for common syntax errors
        for pattern, message in self.SYNTAX_ERROR_PATTERNS:
            if re.search(pattern, cypher, re.IGNORECASE):
                self.errors.append(f"Syntax error: {message}")

        # Check for balanced parentheses and brackets
        if not self._check_balanced(cypher, '(', ')'):
            self.errors.append("Unbalanced parentheses")
        if not self._check_balanced(cypher, '[', ']'):
            self.errors.append("Unbalanced brackets")
        if not self._check_balanced(cypher, '{', '}'):
            self.errors.append("Unbalanced braces")

        # Check for valid node types
        node_types = self._extract_node_types(cypher)
        for node_type in node_types:
            if node_type not in self.VALID_NODE_TYPES:
                self.warnings.append(f"Unknown node type: {node_type}")

        # Check for valid relationships
        relationships = self._extract_relationships(cypher)
        for rel in relationships:
            if rel and rel not in self.VALID_RELATIONSHIPS:
                self.warnings.append(f"Unknown relationship: {rel}")

        # Check for process_id parameter
        if '$process_id' not in cypher and 'process_id' not in cypher:
            self.warnings.append("Missing process_id filter - query may return data from all documents")

        is_valid = len(self.errors) == 0
        return is_valid, self.errors, self.warnings

    def _check_balanced(self, text: str, open_char: str, close_char: str) -> bool:
        """Check if characters are balanced."""
        count = 0
        for char in text:
            if char == open_char:
                count += 1
            elif char == close_char:
                count -= 1
            if count < 0:
                return False
        return count == 0

    def _extract_node_types(self, cypher: str) -> List[str]:
        """Extract node type labels from Cypher."""
        # Pattern: (:Label) or (var:Label) or (var:Label {props})
        pattern = r'\(\s*\w*\s*:\s*(\w+)'
        matches = re.findall(pattern, cypher)
        return list(set(matches))

    def _extract_relationships(self, cypher: str) -> List[str]:
        """Extract relationship types from Cypher."""
        # Pattern: -[:REL_TYPE]-> or -[var:REL_TYPE]->
        pattern = r'-\s*\[\s*\w*\s*:\s*(\w+)\s*\]->'
        matches = re.findall(pattern, cypher)
        return list(set(matches))


# =============================================================================
# NODE TYPE CHECKER
# =============================================================================

class NodeTypeChecker:
    """Checks if Cypher is using the correct node types based on structural probe."""

    def __init__(self):
        self.neo4j_tools = Neo4jTools()

    def check_node_usage(self, cypher: str, expected_node: str, structural_probe: Dict) -> Dict[str, Any]:
        """
        Check if Cypher is using the expected node type.

        Args:
            cypher: Generated Cypher query
            expected_node: Expected node type (e.g., "Cell", "Line", "Cell|Line")
            structural_probe: Results from structural probe

        Returns:
            Dict with analysis results
        """
        result = {
            "expected_node": expected_node,
            "nodes_used": [],
            "is_correct": False,
            "issues": [],
            "recommendations": []
        }

        # Extract node types from Cypher
        node_pattern = r'\(\s*\w*\s*:\s*(\w+)'
        nodes_used = list(set(re.findall(node_pattern, cypher)))
        result["nodes_used"] = nodes_used

        # Check expected nodes
        expected_nodes = expected_node.split("|")

        # Determine which data nodes are used (Cell, Line, Section)
        data_nodes_used = [n for n in nodes_used if n in ['Cell', 'Line', 'Section', 'MergedCell']]

        if not data_nodes_used:
            result["issues"].append("No data nodes (Cell/Line/Section) found in query")
            return result

        # Check if any expected node is used
        for data_node in data_nodes_used:
            if data_node in expected_nodes or 'MergedCell' in expected_nodes and data_node == 'Cell':
                result["is_correct"] = True
                break

        if not result["is_correct"]:
            result["issues"].append(
                f"Expected {expected_node} but query uses {', '.join(data_nodes_used)}"
            )

        # Check against structural probe
        if structural_probe.get("found_in"):
            probe_has_cell = any(
                loc["node_type"] in ["Cell", "MergedCell"]
                for term_locs in structural_probe["found_in"].values()
                for loc in term_locs
            )
            probe_has_line = any(
                loc["node_type"] == "Line"
                for term_locs in structural_probe["found_in"].values()
                for loc in term_locs
            )

            # Check for mismatch between probe and query
            if "Cell" in data_nodes_used and not probe_has_cell and probe_has_line:
                result["issues"].append(
                    "PROBE MISMATCH: Structural probe found data in Line nodes, but query uses Cell"
                )
                result["recommendations"].append("Consider using Line nodes instead of Cell")

            if "Line" in data_nodes_used and not probe_has_line and probe_has_cell:
                result["issues"].append(
                    "PROBE MISMATCH: Structural probe found data in Cell nodes, but query uses Line"
                )
                result["recommendations"].append("Consider using Cell nodes instead of Line")

        return result

    def close(self):
        """Close Neo4j connection."""
        self.neo4j_tools.close()


# =============================================================================
# STRUCTURAL PROBE TESTER
# =============================================================================

def test_structural_probe(process_id: str, search_terms: List[str]) -> Dict[str, Any]:
    """
    Test the structural probe functionality.

    Args:
        process_id: Document UUID
        search_terms: List of terms to search for

    Returns:
        Dict with probe results and analysis
    """
    logger.info(f"Testing structural probe for process_id: {process_id}")
    logger.info(f"Search terms: {search_terms}")

    neo4j_tools = Neo4jTools()

    try:
        probe_result = neo4j_tools.structural_probe(process_id, search_terms)

        analysis = {
            "probe_result": probe_result,
            "node_counts": probe_result.get("node_counts", {}),
            "terms_found": list(probe_result.get("found_in", {}).keys()),
            "recommended_paths": probe_result.get("recommended_paths", []),
            "data_locations": probe_result.get("data_locations", []),
            "issues": []
        }

        # Check if probe found anything
        if not probe_result.get("found_in"):
            analysis["issues"].append("Structural probe found no matching data")

        # Check node counts
        node_counts = probe_result.get("node_counts", {})
        if node_counts.get("cells", 0) == 0 and node_counts.get("lines", 0) == 0:
            analysis["issues"].append("Document has no Cell or Line nodes")

        return analysis

    finally:
        neo4j_tools.close()


# =============================================================================
# HARD CONSTRAINTS TESTER
# =============================================================================

def test_hard_constraints(structural_probe: Dict, weaviate_chunks: List[Dict], user_query: str) -> Dict[str, Any]:
    """
    Test if hard constraints are being correctly extracted.

    Args:
        structural_probe: Results from structural probe
        weaviate_chunks: Weaviate chunks
        user_query: User query

    Returns:
        Dict with constraint analysis
    """
    constraints = extract_hard_constraints(structural_probe, weaviate_chunks, user_query)

    analysis = {
        "constraints": constraints,
        "primary_node": constraints.get("primary_node"),
        "forbidden_nodes": constraints.get("forbidden_nodes", []),
        "required_path": constraints.get("required_path"),
        "reasoning": constraints.get("reasoning", []),
        "issues": []
    }

    # Check if constraints are set
    if not constraints.get("primary_node"):
        analysis["issues"].append("No primary node constraint determined")

    # Check for conflicting constraints
    if constraints.get("primary_node") in constraints.get("forbidden_nodes", []):
        analysis["issues"].append("Primary node is in forbidden nodes list - CONFLICT!")

    return analysis


# =============================================================================
# MAIN TEST RUNNER
# =============================================================================

def run_cypher_validation_tests():
    """Run all Cypher validation tests."""

    print("\n" + "=" * 80)
    print("AGENT E: CYPHER GENERATION VALIDATOR")
    print("=" * 80)
    print(f"Process ID: {PROCESS_ID}")
    print(f"Test queries: {len(TEST_QUERIES)}")
    print(f"Timestamp: {datetime.now().isoformat()}")
    print("=" * 80 + "\n")

    results = {
        "process_id": PROCESS_ID,
        "timestamp": datetime.now().isoformat(),
        "test_results": [],
        "summary": {
            "total_tests": len(TEST_QUERIES),
            "passed": 0,
            "failed": 0,
            "syntax_errors": 0,
            "node_type_mismatches": 0,
            "topology_violations": 0
        }
    }

    syntax_validator = CypherSyntaxValidator()
    node_checker = NodeTypeChecker()

    for i, test_case in enumerate(TEST_QUERIES, 1):
        query = test_case["query"]
        expected_node = test_case["expected_node"]

        print("\n" + "-" * 80)
        print(f"TEST {i}/{len(TEST_QUERIES)}: {query}")
        print(f"Expected node type: {expected_node}")
        print(f"Description: {test_case['description']}")
        print("-" * 80 + "\n")

        test_result = {
            "query": query,
            "expected_node": expected_node,
            "description": test_case["description"],
            "validation_notes": test_case.get("validation_notes", ""),
            "generated_cypher": None,
            "syntax_validation": None,
            "node_type_check": None,
            "topology_check": None,
            "structural_probe": None,
            "hard_constraints": None,
            "execution_result": None,
            "passed": False,
            "issues": []
        }

        try:
            # Step 1: Run the fewshot cypher generation
            print("Step 1: Running fewshot cypher generation...")
            result = run_fewshot_cypher_generation(
                user_query=query,
                process_id=PROCESS_ID,
                max_iterations=2  # Limit iterations for testing
            )

            cypher = result.get("cypher", "")
            test_result["generated_cypher"] = cypher
            test_result["execution_result"] = {
                "success": result.get("success", False),
                "result_count": result.get("result_count", 0),
                "iterations": result.get("iterations", 0),
                "logical_plan": result.get("logical_plan", ""),
                "answer": result.get("answer", "")[:500] if result.get("answer") else None
            }

            print(f"\nGenerated Cypher:\n{'-' * 40}")
            print(cypher[:1000] if cypher else "NO CYPHER GENERATED")
            print(f"{'-' * 40}\n")

            if not cypher:
                test_result["issues"].append("No Cypher query generated")
                results["summary"]["failed"] += 1
                results["test_results"].append(test_result)
                continue

            # Step 2: Validate syntax
            print("Step 2: Validating Cypher syntax...")
            is_valid_syntax, syntax_errors, syntax_warnings = syntax_validator.validate(cypher)
            test_result["syntax_validation"] = {
                "is_valid": is_valid_syntax,
                "errors": syntax_errors,
                "warnings": syntax_warnings
            }

            if not is_valid_syntax:
                test_result["issues"].extend(syntax_errors)
                results["summary"]["syntax_errors"] += 1
                print(f"  SYNTAX ERRORS: {syntax_errors}")
            else:
                print("  Syntax: VALID")

            if syntax_warnings:
                print(f"  Warnings: {syntax_warnings}")

            # Step 3: Test structural probe
            print("\nStep 3: Testing structural probe...")
            search_terms = query.lower().split()[:5]  # First 5 words
            probe_analysis = test_structural_probe(PROCESS_ID, search_terms)
            test_result["structural_probe"] = probe_analysis

            print(f"  Node counts: {probe_analysis.get('node_counts', {})}")
            print(f"  Terms found: {probe_analysis.get('terms_found', [])}")
            print(f"  Recommended paths: {probe_analysis.get('recommended_paths', [])}")

            # Step 4: Test hard constraints
            print("\nStep 4: Testing hard constraints...")
            constraint_analysis = test_hard_constraints(
                probe_analysis.get("probe_result", {}),
                [],  # Empty weaviate chunks for this test
                query
            )
            test_result["hard_constraints"] = constraint_analysis

            print(f"  Primary node: {constraint_analysis.get('primary_node')}")
            print(f"  Forbidden nodes: {constraint_analysis.get('forbidden_nodes')}")
            print(f"  Reasoning: {constraint_analysis.get('reasoning')}")

            # Step 5: Check node type usage
            print("\nStep 5: Checking node type usage...")
            node_analysis = node_checker.check_node_usage(
                cypher,
                expected_node,
                probe_analysis.get("probe_result", {})
            )
            test_result["node_type_check"] = node_analysis

            print(f"  Nodes used: {node_analysis.get('nodes_used')}")
            print(f"  Expected: {expected_node}")
            print(f"  Correct: {node_analysis.get('is_correct')}")

            if not node_analysis.get("is_correct"):
                test_result["issues"].extend(node_analysis.get("issues", []))
                results["summary"]["node_type_mismatches"] += 1

            if node_analysis.get("recommendations"):
                print(f"  Recommendations: {node_analysis.get('recommendations')}")

            # Step 6: Verify topology
            print("\nStep 6: Verifying topology...")
            is_valid_topology, _, topology_violations = verify_topology(
                cypher,
                probe_analysis.get("probe_result", {})
            )
            test_result["topology_check"] = {
                "is_valid": is_valid_topology,
                "violations": topology_violations
            }

            if not is_valid_topology:
                test_result["issues"].extend(topology_violations)
                results["summary"]["topology_violations"] += 1
                print(f"  TOPOLOGY VIOLATIONS: {topology_violations}")
            else:
                print("  Topology: VALID")

            # Determine if test passed
            test_passed = (
                is_valid_syntax and
                is_valid_topology and
                node_analysis.get("is_correct", False) and
                result.get("success", False)
            )
            test_result["passed"] = test_passed

            if test_passed:
                results["summary"]["passed"] += 1
                print("\n>>> TEST PASSED <<<")
            else:
                results["summary"]["failed"] += 1
                print(f"\n>>> TEST FAILED - Issues: {test_result['issues']} <<<")

        except Exception as e:
            logger.error(f"Test execution error: {e}")
            import traceback
            traceback.print_exc()
            test_result["issues"].append(f"Execution error: {str(e)}")
            results["summary"]["failed"] += 1

        results["test_results"].append(test_result)

    # Cleanup
    node_checker.close()

    # Print summary
    print("\n" + "=" * 80)
    print("TEST SUMMARY")
    print("=" * 80)
    print(f"Total tests: {results['summary']['total_tests']}")
    print(f"Passed: {results['summary']['passed']}")
    print(f"Failed: {results['summary']['failed']}")
    print(f"Syntax errors: {results['summary']['syntax_errors']}")
    print(f"Node type mismatches: {results['summary']['node_type_mismatches']}")
    print(f"Topology violations: {results['summary']['topology_violations']}")
    print("=" * 80)

    # Print detailed issues for each query
    print("\n" + "=" * 80)
    print("GENERATED CYPHERS AND ISSUES")
    print("=" * 80)

    for test_result in results["test_results"]:
        print(f"\nQuery: {test_result['query']}")
        print(f"Passed: {test_result['passed']}")
        print(f"Generated Cypher:\n{test_result.get('generated_cypher', 'N/A')[:800]}")
        if test_result.get("issues"):
            print(f"Issues: {test_result['issues']}")
        print("-" * 40)

    # Save results to file
    output_file = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        f"cypher_validation_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    )

    with open(output_file, 'w') as f:
        json.dump(results, f, indent=2, default=str)

    print(f"\nResults saved to: {output_file}")

    return results


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    results = run_cypher_validation_tests()

    # Exit with error code if tests failed
    if results["summary"]["failed"] > 0:
        sys.exit(1)
    else:
        sys.exit(0)
